### ISSUE TITLE
Enhancement: run app via package installation

### ISSUE THREAD

**Issue by Gotfrid** [pharmaverse/aNCA#122]
### Description
Currently to run the app, one has to clone a repository. I think it might be a detractor for some non-technical folks. This is why I believe that we should be able to make it possible to run the app after installing the package from Github.

### Implementation plan
1. Prepare a reproducible environment with docker
2. Update `run_app` function to `require` all required packages
3. Update `run_app` function to be able to pass parameters to the underlying `shiny::runApp` function
4. Add missing imports/packages to the `run_app` function, e.g. `logger`
5. Make sure the app can be installed & run via reproducible environment
6. Update the readme installation section
7. Bump package version

### Definition of Done
- [ ] user can install the package from github via `pak::pak("pharmaverse/aNCA")`
- [ ] user can run the app via `aNCA::run_app()`
- [ ] README contains information on how to install & run the app
- [ ] Package version is bumped
